export const carListNew = [
  {
    name: "BMW iX",
    series: "ix",
    path: "/all-car-new-png/ix.webp",
    type: "electric",
    tag: "suv",
    title: "Expressive and electric. Trailblazing a new age.",
    description:
      "The new BMW iX confidently takes the lead. It provides total flexibility on longer journeys too with a pure electric range of up to 602 km.¹ The clear lines and modernity of the new exterior lend the vehicle a unique design vocabulary, and the spaciousness, comfort and exclusiveness of the interior are just as inspiring. The driver assistance systems are only noticeable by making every journey simpler, safer and more pleasant. Discover all the model variants of the new BMW iX, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "300 kW (408 hp)",
      "0-100 km/h": "5.1s",
      vmax: "200 km/h",
      range: "490 - 602 km",
    },
    // heroImage: "/car-list/ix.webp",
  },
  {
    name: "BMW iX3",
    series: "ix3",
    path: "/all-car-new-png/ix3.webp",
    type: "electric",
    tag: "suv",
    description: `The generously proportioned exterior and interior of the new BMW iX3 clearly highlights the brand's unmistakable design features and, in combination with a modern interior experience and BMW's typical driver orientation, creates maximum comfort. With a range of up to 805 km¹ and 400 kW² charging power, the BMW iX3 50 xDrive sets new standards in the fully electric SUV segment. The innovative BMW Panoramic iDrive takes intuitive operation and driver orientation to a new level. With the BMW Heart of Joy and optimized driver assistance systems, a new level of driving pleasure is achieved.`,
    title: "New design language. Clear, distinctive, and timeless.",
    content: {
      power: "300 kW (408 hp)",
      "0-100 km/h": "4.9s",
      vmax: "210 km/h",
      range: "490 - 602 km",
    },
    // heroImage: "/car-list/ix3.webp",
  },
  {
    name: "BMW iX1",
    series: "ix1-suv",
    path: "/all-car-new-png/ix1-suv.webp",
    type: "electric",
    tag: "suv",
    title: "Driving Pleasure.",
    description:
      "For your everyday commute or weekend away – the BMW iX1 is your fully electric companion for every kind of adventure. And visually unmistakable from every angle. Enjoy spaciousness and comfort on every seat. Discover all the model variants of the BMW iX1, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "150 kW (204 hp)",
      "0-100 km/h": "8.6s",
      vmax: "170 km/h",
      range: "417 - 439 km",
    },
    // heroImage: "/car-list/ix1.webp",
  },
  {
    name: "BMW i7 Sedan",
    series: "i7-sedan",
    path: "/all-car-new-png/i7-sedan.webp",
    type: "electric",
    tag: "sedan",
    title: "Driving Pleasure.",
    description:
      "The BMW i7 Sedan takes the lead in every regard, from technology and design to comfort and a confident presence on the road. All without local emissions, thanks to its innovative, fully electric drive system that generates nothing but pure driving pleasure, whether you are behind the wheel or in the rear. Discover all the model variants of the BMW i7 Sedan, its equipment options and technical data, plus numerous leasing and financing options.",
    // content: {
    //   power: "485 kW (660 hp)",
    //   "0-100 km/h": "3.7s",
    //   vmax: "200 km/h",
    //   range: "490 - 602 km",
    // },
    // heroImage: "/car-list/i7-sedan.webp",
  },
  {
    name: "BMW i5 Sedan",
    series: "i5-sedan",
    path: "/all-car-new-png/i5-sedan.webp",
    type: "electric",
    tag: "sedan",
    title: "Sustainable Performance",
    description:
      "The BMW i5 contributes to a more sustainable future. We use secondary materials and green energy during production, optimising the CO2 footprint of the BMW i5 even before we hand it over to you. The BMW Vehicle Footprint offers information along the entire life cycle of a BMW. Get an overview of selected ecological and social effects of your vehicle based on the main parameters.",
    content: {
      power: "340 kW",
      "0-100 km/h": "6s",
      vmax: "193 km/h",
      range: "up to 582 km",
    },
    heroImage: "/car-list/i5-sedan.png",
  },
  {
    name: "BMW i5 Touring",
    series: "i5-touring",
    path: "/all-car-new-png/i5-touring.webp",
    type: "electric",
    tag: "touring",
    description: `You'll reach your destinations on battery power alone with the BMW i5 Touring. And conveniently fit everything in, as it has plenty of space for whatever you are planning. Discover all the model variants of the BMW i5 Touring, its equipment options and technical data, plus numerous leasing and financing options.`,
    title: "FULLY ELECTRIC FOR BIG PLANS",
    content: {
      power: "250 kW (340 hp)",
      "0-100 km/h": "6.1s",
      vmax: "193 km/h",
      range: "up to 560 km",
    },
  },
  {
    name: "BMW i4 SUV",
    series: "i4-suv",
    path: "/all-car-new-png/i4-suv.webp",
    type: "electric",
    tag: "suv",
    title: "Driving Pleasure.",
    description: `You will hit the road with a sporty look and 100% battery power in the BMW i4 Gran Coupé. Leave a lasting impression, not emissions. The redesigned front accentuates the athletic nature of the vehicle. Elegant rear lights provide pleasing aesthetics at the rear. A contemporary atmosphere is conveyed by the new steering wheel design and waterfall ambient lighting in the interior. Discover all the model variants of the BMW 4 Series Gran Coupé, its equipment options and technical data, plus numerous leasing and financing options.`,
    content: {
      power: "210 kW (286 hp)",
      "0-100 km/h": "6s",
      vmax: "190 km/h",
      range: "406 - 500 km",
    },
  },
  {
    name: "BMW XM SUV",
    series: "xm-suv",
    path: "/all-car-new-png/xm-suv.webp",
    type: "electric",
    tag: "hybrid",
    title: "For those who want more",
    description:
      "An extrovert from the front to the rear. Powerful proportions and striking design elements. Top performance of up to 550 kW (738 hp)³. The BMW XM Label and BMW XM 50e set new benchmarks in the high-performance segment, combining the power typical of M models with advanced plug-in hybrid technology. Discover all the model variants of the new BMW XM, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "550 kW (738 hp)",
      "0-100 km/h": "3.2s",
      vmax: "250 km/h",
      range: "up to 560 km",
    },
  },
  {
    name: "BMW X7 SUV",
    series: "x7-suv",
    path: "/all-car-new-png/x7-suv.webp",
    type: "petrol",
    tag: "suv",
    description:
      "Discover all the model variants of the BMW X7, its equipment options and technical data, plus numerous leasing and financing options.",
    title: "Driving Pleasure.",
    content: {
      power: "280 kW (381 hp)",
      "0-100 km/h": "5.8s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW X6 SUV",
    series: "x6-suv",
    path: "/all-car-new-png/x6-suv.webp",
    type: "petrol",
    tag: "suv",
    title: "Driving Pleasure.",
    description:
      "A powerful presence. The BMW X6 enthrals with its distinctive design, coupé-styled profile and technical sophistication. Its contoured front boasting an illuminated kidney grille, its flowing roof line and cleanly drawn rear form a silhouette simply brimming with character. Behind this expressive appearance lies dynamic BMW performance: with powerful engines, adaptive suspension and intelligent all-wheel drive.",
    content: {
      power: "280 kW (381 hp)",
      "Max. torque": "540 Nm",
      "0-100 km/h": "5.4s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW X5 SUV",
    series: "x5-suv",
    path: "/all-car-new-png/x5-suv.webp",
    type: "petrol",
    tag: "suv",
    title: "Driving Pleasure.",
    description:
      "The BMW X5 fuses aesthetics with performance, comfort, and versatility, around town, on long journeys, or off-road. Its agile steering and precise power delivery ensure that the BMW X5 adapts to every driving situation. In terms of appearance, it exudes self-confidence, with wide proportions, an unmistakable character line, and horizontal contours. Discover all the model variants of the BMW X5, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "280 kW (381 hp)",
      "0-100 km/h": "5.4s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW X4 SUV",
    series: "x4-suv",
    path: "/all-car-new-png/x4-suv.webp",
    type: "petrol",
    tag: "suv",
    title: "Driving Pleasure.",
    description:
      "The BMW X4 stands out confidently from the crowd with its striking design: With the high-quality accessories from BMW M Performance Parts, you can emphasise the sporty character of this distinctive Sports Activity Coupé.",
    content: {
      "Engine power (hp) at 1/min": "252/5,200-6,500",
      "Fuel consumption combined in km/l": "8.3",
      "CO2 combined emissions in g/km": "180",
    },
  },
  {
    name: "BMW X3 SUV",
    series: "x3-suv",
    path: "/all-car-new-png/x3-suv.webp",
    type: "petrol",
    tag: "suv",
    title: "Built to explore the world.",
    description:
      "The BMW X3 combines comfort, everyday flexibility, and unique, characteristically X driving dynamics. Innovative in-car connectivity and driver assistance technologies take functionality, safety and entertainment to a new level in the BMW X3. Its design sets standards with highlight features such as the reinterpreted BMW kidney Iconic Glow. And with an impressive luggage compartment capacity, the BMW X3 has space for whatever you want to take with you. Discover all the model variants, equipment options and technical data, or configure the BMW X3 according to your individual requirements.",
    content: {
      power: "153 kW (208 hp)",
      "0-100 km/h": "8.5s",
      vmax: "215 km/h",
    },
  },
  {
    name: "BMW X1 SUV",
    series: "x1-suv",
    path: "/all-car-new-png/x1-suv.webp",
    type: "petrol",
    tag: "suv",
    title: "Driving Pleasure.",
    description:
      "Versatile enough to be an urban all-rounder and a sporting performer. For drivers who do not want to compromise. The BMW X1 delivers the perfect balance of style, comfort and power. Discover all the model variants of the BMW X1, their equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "115 kW (156 hp)",
      "0-100 km/h": "9s",
      vmax: "215 km/h",
    },
  },
  {
    name: "BMW 7 Sedan",
    series: "7-sedan",
    path: "/all-car-new-png/7-sedan.webp",
    type: "petrol",
    tag: "sedan",
    title: "Driving pleasure.",
    description:
      "The BMW 7 Series combines elegant design with precise, powerful dynamics and technical innovations that bring joy with every journey. Whether you sit behind the wheel or in the rear, there is plenty of room for unique driving experiences. Discover all the model variants of the BMW 7 Series, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "210 kW (286 hp)",
      "0-100 km/h": "6.7s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW 5 Sedan",
    series: "5-sedan",
    path: "/all-car-new-png/5-sedan.webp",
    type: "petrol",
    tag: "sedan",
    title: "Driving Pleasure.",
    description:
      "The BMW 5 Series Sedan combines sporty elegance with innovative technology. Experience the perfect balance of performance, comfort, and efficiency in this iconic executive sedan.",
    content: {
      power: "140 kW (hp)",
      "0-100 km/h": "8.1s",
      torque: "310 Nm",
      vmax: "193 km/h",
    },
  },
  {
    name: "BMW M4 Coupe",
    series: "m4-coupe",
    path: "/all-car-new-png/m4-coupe.webp",
    type: "petrol",
    tag: "coupe",
    title: "THE BMW 4 SERIES COUPÉ M MODELS.",
    description:
      "The M Coupé model series combine aesthetics and the sportiness you have come to expect from BMW M. A wealth of technologies from the motorsports sector enhance the driving dynamics of these models, thus delivering on the racetrack as well as in everyday driving. The power ranges from 390 kW (523 hp) in the BMW M4 Competition Coupé M xDrive to a mighty 405 kW (543 hp) in the BMW M4 CS. Discover the BMW 4 Series Coupé M models, their exciting equipment options, technical data, and a wide range of leasing and financing options.",
    content: {
      power: "405 kW (543 hp)",
      torque: "650 Nm",
      "0-100 km/h": "3.4s",
      vmax: "302 km/h",
    },
  },
  {
    name: "BMW 4 Gran Coupe",
    series: "4-gran-coupe",
    path: "/all-car-new-png/4-gran-coupe.webp",
    type: "petrol",
    tag: "Gran Coupe",
    title: "YOUR IRRESISTABLE SPORTY EVERYDAY COMPANION.",
    description:
      "The new BMW 4 Series Coupé attracts admiring glances wherever it goes. On the exterior, its powerful kidney grille and slimline headlights give an initial indication of its persuasive power. And the sporty and functional design in the interior of the standard equipment cannot fail to impress. It’s time to discover all the model variants of the new BMW 4 Series Coupé, its equipment options and technical data, plus a wealth of leasing and financing options.",
    content: {
      power: "190 kW (255 hp)",
      torque: "400 Nm",
      "0-100 km/h": "5.9s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW 4 Convertible",
    series: "4-convertible",
    path: "/all-car-new-png/4-convertible.webp",
    type: "petrol",
    tag: "convertible",
    title: "ALL SET FOR SPORTY EXPERIENCES.",
    description:
      "The new BMW 4 Series Convertible shows how elegantly an athletic presence and everyday driving practicality can be combined. Its irresistible exterior design exudes style with a powerful double kidney grille and narrow headlights. Its interior is comfortable and sophisticated, even with the standard equipment. Discover all the model variants of the new BMW 4 Series Convertible, its equipment options and technical data, plus a wealth of leasing and financing options.",
    content: {
      power: "190 kW (255 hp)",
      torque: "400 Nm",
      "0-100 km/h": "6.4s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW M4 Convertible",
    series: "m4-convertible",
    path: "/all-car-new-png/m4-convertible.webp",
    type: "petrol",
    tag: "convertible",
    title: "THE BMW 4 SERIES CONVERTIBLE M MODELS.",
    description:
      "The BMW 4 Series convertible M model series are the perfect symbiosis of power and aesthetic design. A wealth of technologies from the motorsport sector deliver extremely agile driving dynamics and outstanding power, both on the racetrack and on the road. Discover exciting equipment options, technical data and a wide range of leasing and financing options for the BMW 4 Series convertible M models.",
    content: {
      power: "390 kW (523 hp)",
      torque: "650 Nm",
      "0-100 km/h": "3.7s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW 3 Sedan",
    series: "3-sedan",
    path: "/all-car-new-png/3-sedan.webp",
    type: "petrol",
    tag: "sedan",
    title: "Driving Pleasure.",
    description:
      "The BMW 3 Series Sedan combines a dynamic driving feel with a modern interior. Innovative technologies and intelligent driver assistance systems transform every journey into an unforgettable experience. The exterior of the BMW 3 Series Sedan is sporty and elegant. The facelift in the interior offers full comfort and can be operated intuitively. Discover all the model variants of the BMW 3 Series Sedan, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "135 kW (184 hp)",
      torque: "300 Nm",
      "0-100 km/h": "7.4s",
      vmax: "235 km/h",
    },
  },
  {
    name: "BMW M3 Sedan",
    series: "m3-sedan",
    path: "/all-car-new-png/m3-sedan.webp",
    type: "petrol",
    tag: "sedan",
    title: "The BMW 3 Series Sedan M models.",
    description:
      "M-typical performance, innovative technologies and exciting design: every facet of the 3 Series M Sedans reflects their motorsport pedigree. From the powerfully accelerating BMW M340d xDrive Sedan delivering 250 kW (340 hp) to the mighty BMW M3 Competition Sedan with M xDrive delivering 390 kW (523 hp), every model delivers an adrenaline-charged drive. Discover the BMW 3 Series Sedan M models, their equipment options, technical data, and a wide range of leasing and financing options.",
    content: {
      power: "390 kW (523 hp)",
      torque: "650 Nm",
      "0-100 km/h": "3.5s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW M3 Touring",
    series: "m3-touring",
    path: "/all-car-new-png/m3-touring.webp",
    type: "petrol",
    tag: "touring",
    title: "The BMW 3 Series Touring M models.",
    description:
      "BMW 3 Series Touring M models combine sporty performance with striking M design and everyday driving practicality. Discover the equipment options and technical data of the BMW M3 CS Touring, BMW M3 Competition Touring, BMW M340i xDrive Touring and BMW M340d xDrive Touring, plus numerous leasing and financing options.",
    content: {
      power: "405 kW (543 hp)",
      torque: "650 Nm",
      "0-100 km/h": "3.5s",
      vmax: "300 km/h",
    },
  },
  {
    name: "BMW 2 Coupe",
    series: "2-coupe",
    path: "/all-car-new-png/2-coupe.webp",
    type: "petrol",
    tag: "coupe",
    title: "Palpably sporty. Focus on driving pleasure.",
    description:
      "The design of the BMW 2 Series Coupé is the epitome of sportiness. Even when stationary, its muscular front, short rear and clean lines exude dynamism. A driver-focused cockpit with a host of high-quality details awaits you in the interior. Discover the BMW 2 Series Coupé, its equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "135 kW (181 hp)",
      torque: "300 Nm",
      "0-100 km/h": "7.5s",
      vmax: "236 km/h",
    },
  },
  {
    name: "BMW M2 Coupe",
    series: "m2-coupe",
    path: "/all-car-new-png/m2-coupe.webp",
    type: "petrol",
    tag: "coupe",
    title: "BMW 2 Series Coupé M Models.",
    description:
      "Sheer racing thrills in the compact car segment. A wealth of technologies from the world of motorsport enhances its precision and driving dynamics. Its powerful performance is pushed to an outstanding 353 kW (480 hp) in the new BMW M2 Coupé. Discover the BMW 2 Series Coupé M models, their exciting equipment options, technical data, and a wide range of leasing and financing options.",
    content: {
      power: "353 kW (480 hp)",
      torque: "550 Nm",
      "0-100 km/h": "4.2s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW 2 Gran Coupe",
    series: "2-gran-coupe",
    path: "/all-car-new-png/2-gran-coupe.webp",
    type: "petrol",
    tag: "Gran Coupe",
    title: "Strikingly sporty. Inspiring design.",
    description:
      "The BMW 2 Series Gran Coupé’s elongated silhouette with frameless side windows attracts attention. From everyday driving to epic adventures, dynamic engines deliver the perfect mix of sportiness and comfort, while digital assistants make the driving experience safer. Discover all the model variants of the new BMW 2 Series Gran Coupé, their equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "110 kW (150 hp)",
      "0-100 km/h": "8.4s",
      vmax: "226 km/h",
    },
  },
  {
    name: "BMW Z4 Roadster",
    series: "z4-roadster",
    path: "/all-car-new-png/z4-roadster.webp",
    type: "petrol",
    tag: "roadster",
    title: "Driving pleasure.",
    description:
      "Built for bends, straights, and everything in between. The BMW Z4 Roadster embodies everything that is fun about a BMW – in its design, its equipment and especially on the road. The standard M aerodynamic package makes it even more dynamic, while features such as the M Sport seats in the interior generate more excitement. Discover the model variants, individual equipment options and attractive leasing and financing offers.",
    content: {
      power: "190 kW (255 hp)",
      torque: "295 Nm",
      "0-100 km/h": "5.4s",
      vmax: "250 km/h",
    },
  },
  {
    name: "BMW Z4 Roadster 2",
    series: "z4-roadster-2",
    path: "/all-car-new-png/z4-roadster-2.webp",
    type: "petrol",
    tag: "roadster",
    title: "Driving pleasure.",
    description:
      "The BMW Z4 M40i Roadster is all about direct and powerful dynamics on the road. This is reflected in its design, equipment and, above all, in its drivability. Thanks to its low centre of gravity and balanced weight distribution, hit the curve just right. Selected materials and intelligent technologies in the interior create an ambience that fuses comfort with control. Discover all model variants, equipment options and technical data, plus numerous leasing and financing options.",
    content: {
      power: "285 kW (382 hp)",
      torque: "500 Nm",
      "0-100 km/h": "4.6s",
      vmax: "250 km/h",
    },
  },
];
